name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7.x.x

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - uses: supabase/setup-cli@v1
        with:
          version: 1.77.4

      - name: Start Supabase
        run: supabase start

      - name: 🦺 Check Format and Lint
        id: static
        run: pnpm run turbo format:check lint:report
        continue-on-error: true

      - name: 💍 Merge lint reports
        run: |
          shopt -s globstar
          jq -s '[.[]]|flatten' ./**/lint-results/*.json &> eslint_report.json

      - name: 👸 Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
        continue-on-error: true

      - name: ☁️ Upload ESLint report
        uses: actions/upload-artifact@v3
        with:
          name: eslint_report.json
          path: eslint_report.json
        continue-on-error: true

      - name: 📦 Build Packages
        id: build
        run: pnpm run build:packages
        continue-on-error: true

      - name: 🚧 Test
        id: test
        run: pnpm run test
        continue-on-error: true

      - name: Upload postgrest-core coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/postgrest-core/coverage/coverage-final.json
          flags: postgrest-core
          fail_ci_if_error: false

      - name: Upload postgrest-react-query coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/postgrest-react-query/coverage/coverage-final.json
          flags: postgrest-react-query
          fail_ci_if_error: false

      - name: Upload postgrest-swr coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/postgrest-swr/coverage/coverage-final.json
          flags: postgrest-swr
          fail_ci_if_error: false

      - name: Upload storage-core coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/storage-core/coverage/coverage-final.json
          flags: storage-core
          fail_ci_if_error: false

      - name: Upload storage-swr coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/storage-swr/coverage/coverage-final.json
          flags: storage-swr
          fail_ci_if_error: false

      - name: Upload storage-react-query coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./packages/storage-react-query/coverage/coverage-final.json
          flags: storage-react-query
          fail_ci_if_error: false

      - name: ⚠️ Check for error
        if: steps.static.outcome != 'success' || steps.build.outcome != 'success' || steps.test.outcome != 'success'
        run: exit 1
