name: Release @next

on:
  push:
    branches:
      - next
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7.x.x

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Packages
        run: pnpm run build --filter='./packages/*'

      - name: Create a release
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version --snapshot next
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:release --tag next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
